### ISSUE TITLE
use setuptools for demo python package

### ISSUE THREAD

**Issue by edavidaja** [rstudio/package-manager-demo#23]

**Comment by SamEdwardes** [comment]
Can you say more about what needs to be added?

**Comment by edavidaja** [comment]
As in, instead of hatch: https://github.com/rstudio/package-manager-demo/blob/main/python-package-manager-demo/pyproject.toml#L1-L4

Adding hatch to the list of td dependencies does not result in being able to build the package.

**Comment by SamEdwardes** [comment]
After some experimentation, I do not think using setuptools will help. The issue was that the repo that contained the demo package did not have a hatchling (or any other Python packages available). The fix is to ensure that pip has access to the required packages needed to build the demo package (whether that be hatchling or setuptools).

```bash
pip config set global.index-url https://enchanted-axolotl.staging.eval.posit.co/pkg/pypi/latest/simple
pip config set global.extra-index-url https://enchanted-axolotl.staging.eval.posit.co/pkg/internal-python/latest/simple
pip config set global.trusted-host https://enchanted-axolotl.staging.eval.posit.co

pip install package-manager-demo
```
